"""Added initial ta

Revision ID: 6efe52d555fa
Revises: fc0884552e15
Create Date: 2022-06-04 22:09:38.679571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efe52d555fa'
down_revision = 'fc0884552e15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
