"""Added initial tabl

Revision ID: ed8dd3b2c9ae
Revises: 83d1fbf0a583
Create Date: 2022-06-04 19:01:22.816443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed8dd3b2c9ae'
down_revision = '83d1fbf0a583'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_user_id_fkey', 'folders', type_='foreignkey')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('folders_user_id_fkey', 'folders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
