"""Added initial t

Revision ID: fccb96b8b940
Revises: 6efe52d555fa
Create Date: 2022-06-04 22:11:46.470075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fccb96b8b940'
down_revision = '6efe52d555fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('folders_user_id_fkey', 'folders', type_='foreignkey')
    op.drop_column('folders', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('folders_user_id_fkey', 'folders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
